### ISSUE TITLE
'Sticky' param doesn't support boolean value true without quotation, false however works

### ISSUE THREAD

**Issue by mutasim** [home-assistant/mobile-apps-fcm-push#7]
**Home Assistant Android version: 1.7.0**

After wrestling with this for some time I've managed to deduce the following, the 'sticky' param doesn't support the value true without quotations.

E.g. this doesn't work:

```yaml
message: 'Would you like to unlock the door?'
title: 'Welcome Home'
data:
    sticky: true
```
The notification doesn't send, and I didn't see any error messages.

However the following does work:

`sticky: false`
`sticky: 'true'`
`sticky: 'false'`
